first version
urfu-2018/javascript-task-5 pull request #23
Opened 2018-11-11 12:55 UTC by KartsevYaroslav

2018-11-11 12:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2018-11-11 13:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 13:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2018-11-11 13:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 24

2018-11-11 14:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 24

2018-11-11 14:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 14:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 24

2018-11-11 15:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 15:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 7 из 24

2018-11-11 19:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-11 19:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-25 20:48 UTC, spt30 requested changes
🍅Пара правок по стилю кода

2018-11-25 20:48 UTC, spt30 commented on lib.js
> +    queue
лучше на этой же строчке начать писать

2018-11-25 20:48 UTC, spt30 commented on lib.js
> +        .sort(
тут тоже

2018-11-25 20:48 UTC, spt30 commented on lib.js
> +    this.filter = x => x.gender === 'male';
можно сразу `this.filter = ({ gender }) => gender === 'male';`

2018-12-02 11:11 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-04 15:11 UTC, spt30 commented
🍏

2018-12-04 15:11 UTC, closed without merging