Ермаков Степан
urfu-2018/javascript-task-5 pull request #29
Opened 2018-11-11 20:04 UTC by predatorfromekb

задача

2018-11-11 20:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 24

2018-11-11 20:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-11 20:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-11 20:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-11 21:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 21:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-11 21:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-11 22:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-11 22:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-11 22:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-11 22:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-11 22:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-11 22:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 24

2018-11-12 18:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-12 19:23 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-12 19:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-12 19:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-12 19:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-12 19:32 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-12 20:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 24

2018-11-12 20:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 24

2018-11-12 20:48 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 24

2018-11-12 21:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-08 12:12 UTC, VasiliiKuznecov requested changes

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +    this.friendsWrapper = filterAndOrder(friends, filter);
что значит friendsWrapper? это же типо собранные друзья просто, причем тут wrapper?

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +        return friendsWrapper.friends.length === friendsWrapper.current;
почему бы friends и current сразу в this и не хранить?

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +    return a.name < b.name ? -1 : 1;
есть специальная функция localeCompare

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +function internal(currentLevel, sortedFriends, result, i) {
функция непонятно названа

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +    const el = sortedFriends.splice(i, 1)[0];
не используй сокращения
что вообще за el?

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +        const q = result
что за q?

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +            .filter(r => r.level === currentLevel - 1)
что за r?

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +function internal(currentLevel, sortedFriends, result, i) {
в этой функции ничего не понял
очень запутанная

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +function flat(accumulator, currentValue) {
это просто concat
не очень понимаю зачем делать из этого отдельную функцию

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +        .map(f => {
не используй сокращения

2018-12-08 12:12 UTC, VasiliiKuznecov commented on lib.js
> +                level: Infinity
что за уровень при друге, это нам точно нужно? выглядит как усложнение

2018-12-13 17:48 UTC, predatorfromekb commented on lib.js
> +                level: Infinity
это на каком круге добавился друг

2018-12-13 18:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-13 18:52 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-13 19:03 UTC, predatorfromekb commented
я поправил все, кроме замечания про concat

на просторах интернета нашел как в js делать из массива массивов один массив
https://stackoverflow.com/questions/10865025/merge-flatten-an-array-of-arrays-in-javascript

через concat

мне кажется, выглядит немного некрасиво, но если надо то сделаю

2018-12-13 19:03 UTC, predatorfromekb commented
🍏

2018-12-26 04:43 UTC, closed without merging