Щупаков Антон
urfu-2018/javascript-task-5 pull request #3
Opened 2018-11-09 13:24 UTC by a-shchupakov

2018-11-09 13:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 24

2018-11-10 05:52 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-14 06:04 UTC, nikshel requested changes
Тебе явно стоит перечитать лекцию по прототипам

2018-11-14 06:04 UTC, nikshel commented on lib.js
> +}
Всю эту функцию можно заменить на одну строчку с `.filter()`

2018-11-14 06:04 UTC, nikshel commented on lib.js
> +    Object.setPrototypeOf(bestFriendFilter, new Filter());
Использовать так `setPrototypeOf` - неправильно

2018-11-14 06:04 UTC, nikshel commented on lib.js
> +    if (filter.constructor !== Filter) {
1. Это неправильный способ проверять наследование. Есть специальный оператор
1. Вообще говоря в `filter.constructor` должен быть либо `MaleFilter`, либо `FemaileFilter`, либо еще что-угодно. Главное, чтобы `Filter` был в цепочке наследования

2018-11-14 06:04 UTC, nikshel commented on lib.js
> +    this.next = function () {
Тут нужно использовать прототипы. В реальной жизни никто не объявляет все функции в конструкторе

2018-11-14 06:04 UTC, nikshel commented on lib.js
> +    const limitedIterator = Object.create(new Iterator(friends, filter));
Использовать так `Object.create` - неправильно

2018-11-14 15:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-14 15:26 UTC, a-shchupakov commented
По-моему какая-то вменяемая инфа по указанию прототипов к функциям-конструкторам (и вообще использование этих функций) появилась только на вчерашней лекции по JS

2018-11-15 09:58 UTC, nikshel commented
Ты прав, что-то напутали с порядком задач 😞 
Но отступать уже поздно

2018-11-15 14:38 UTC, a-shchupakov commented
Уже попытался исправить (если ты вдруг не заметил два коммита) :)

2018-11-16 10:53 UTC, nikshel approved these changes

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +Iterator.prototype.done = function () {
Обычно прототипы объявляют прямо под конструктором

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +LimitedIterator.prototype.constructor = LimitedIterator;
Можно было это в одну строчку написать, `Object.create` вторым аргументом принимает конфигурацию полей

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +    return friends.slice().sort(function (a, b) {
Может стрелочную функцию использовать?

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +    // Линтер ругается, если использовать this здесь, поэтому придется передавать его явно
И правильно делает.
Тебе просто стоит перенести `getNextCycle` в прототип `Iterator`

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +    this.currentFriendCycle = friends.filter((friend) => friend.best);
Скобочки вокруг `friend` можно не опустить

2018-11-16 10:53 UTC, nikshel commented on lib.js
> +    this.isSuitable = function (friend) {
`isSuitable` тоже желательно в прототипы перенести

2018-11-16 10:53 UTC, closed without merging