js-task-5
urfu-2018/javascript-task-5 pull request #34
Opened 2018-11-12 04:51 UTC by VicClone

2018-11-12 04:53 UTC, honest-hrundel commented
:tomato: Превышено максимальное время выполнения тестов

2018-11-12 04:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 2 из 24

2018-11-12 11:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 24

2018-11-12 11:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-12 11:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 24

2018-11-12 11:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-12 11:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 24

2018-11-12 11:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 24

2018-11-12 11:57 UTC, VicClone commented
:bell:

2018-11-12 13:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-12 14:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 24

2018-11-12 14:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 24

2018-11-12 16:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 16:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 16:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 17:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 17:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-12 17:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 17:25 UTC, VicClone commented
:bell:

2018-11-12 17:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 18:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 18:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-12 18:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 18:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 18:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-14 05:54 UTC, nikshel requested changes

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +
Лишняя пустая строчка?

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +    this.next = () => {
Подразумевается, что тут ты используешь возможности прототипов (никто не объявляет все функции в конструкторе)

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +        .reduce((arrNames, currentFriend) => arrNames.concat(currentFriend.friends), [])
`arrNames` - не очень хорошее имя для переменной. Лучше просто `names`. Также в `reduce` часто используют имя `acc`/`accumulator`

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +    while (countCicle < maxLevel && currentRound.length > 0 && maxLevel > 0) {
А нужна ли последняя проверка на `maxLevel`?

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +        invitedFriends = invitedFriends.concat(currentRound);
Можно сделать `invitedFriends.push(...currentRound)`, чтобы добавить в массив, не создавая новый

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +        return !(this.count < this.invitedFriends.length);
Может лучше проверять на равенство?

2018-11-14 05:54 UTC, nikshel commented on lib.js
> +Object.setPrototypeOf(LimitedIterator.prototype, Iterator.prototype);
👍 
Но лучше перенести этот код пониже, чтобы лучше читалось

2018-11-19 13:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2018-11-19 13:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2018-11-19 13:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-19 13:20 UTC, VicClone commented on lib.js
> +
Да, убрал

2018-11-19 13:20 UTC, VicClone commented on lib.js
> +    this.next = () => {
Переписал в прототипы

2018-11-19 13:20 UTC, VicClone commented on lib.js
> +        .reduce((arrNames, currentFriend) => arrNames.concat(currentFriend.friends), [])
Поменял имена

2018-11-19 13:20 UTC, VicClone commented on lib.js
> +    while (countCicle < maxLevel && currentRound.length > 0 && maxLevel > 0) {
Оказалось, не нужна)

2018-11-19 13:21 UTC, VicClone commented on lib.js
> +        invitedFriends = invitedFriends.concat(currentRound);
:+1:

2018-11-19 13:23 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-19 13:24 UTC, VicClone commented on lib.js
> +        return !(this.count < this.invitedFriends.length);
Изменил

2018-11-19 13:24 UTC, VicClone commented on lib.js
> +Object.setPrototypeOf(LimitedIterator.prototype, Iterator.prototype);
Перенес ниже

2018-11-20 07:19 UTC, nikshel approved these changes
👍

2018-11-20 07:19 UTC, closed without merging