df
urfu-2018/javascript-task-5 pull request #49
Opened 2018-11-12 17:55 UTC by Ropedann

2018-11-12 17:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2018-11-12 18:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 18:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 19:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 19:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-12 19:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-15 20:14 UTC, SemyonMakhaev requested changes
🍅 

Привет! Есть небольшое замечание

2018-11-15 20:14 UTC, SemyonMakhaev commented on lib.js
> +    if (!(filter instanceof Filter)) {
Эта проверка выполнится в `Iterator`, можно избавиться от дублирования

2018-12-30 11:00 UTC, closed without merging