1st attempt
urfu-2018/javascript-task-5 pull request #60
Opened 2018-11-13 06:39 UTC by Nerzull3

2018-11-13 06:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 24

2018-11-13 07:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-13 07:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-17 18:06 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-19 06:36 UTC, SemyonMakhaev requested changes
🍅

2018-11-19 06:36 UTC, SemyonMakhaev commented on lib.js
> +    let temporaryListOfFriends = friends
Почему не `const`?

2018-11-19 06:36 UTC, SemyonMakhaev commented on lib.js
> +            .sort((personName1, personName2) => personName1.localeCompare(personName2))
Функция сортировки используется несколько раз, можно её задекларировать снаружи

2018-11-19 06:36 UTC, SemyonMakhaev commented on lib.js
> +        guests.every(friend => friendName !== friend.name)))];
Можешь примерно оценить сложность такой реализации? Получится ли сделать более эффективно?

2018-11-19 07:28 UTC, Nerzull3 commented on lib.js
> +    let temporaryListOfFriends = friends
я присваиваю этому списку в цикле while новое значение

2018-11-19 07:31 UTC, Nerzull3 commented on lib.js
> +            .sort((personName1, personName2) => personName1.localeCompare(personName2))
Изначально хотел так сделать, но потом понял, что в одном месте у меня используется список с объектами, а в другом - с именами. Я подумаю, как можно переписать

2018-11-19 08:47 UTC, SemyonMakhaev commented on lib.js
> +    let temporaryListOfFriends = friends
Ок

2018-11-19 08:47 UTC, SemyonMakhaev commented on lib.js
> +            .sort((personName1, personName2) => personName1.localeCompare(personName2))
👍

2018-11-19 11:35 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-20 06:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-20 06:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 24

2018-11-20 06:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-11-20 19:10 UTC, SemyonMakhaev approved these changes
🍏

2018-11-20 19:10 UTC, closed without merging