please
urfu-2018/javascript-task-5 pull request #68
Opened 2018-11-13 09:50 UTC by strota

2018-11-13 09:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-11-13 09:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-13 10:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2019-01-04 22:30 UTC, chrighter requested changes

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +function searchFriends(newFriendsList, cheackList, friends, nowValue) {
`nowValue` - непонятное именование переменной

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +        if (count && !cheackList.includes(element)) {
`cheackList` -> `checkList` ?

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +        let count = nowValue.friends.includes(element.name);
Неединообразно - почему ты в условии левую часть вынесла в переменную, а правую нет?

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +    while (maxLevel !== 0 && bestFriendsList.length && maxLevel > 0) {
Зачем проверка `maxLevel !== 0`, если есть `maxLevel > 0`?

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +    return friend.sort(function (a, b) {
`(a, b) => a.name < b.name`

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +    let bestFriendsList = bestFriends(friends);
Функции обычно именуют с помощью глаголов

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +    let newFriendsList = [];
`finalFriendsList`, `newFriendsList` - непонятно

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +    return sorts(friends.filter(f => f.best));
Не нужно именовать переменные одной буквой

2019-01-04 22:30 UTC, chrighter commented on lib.js
> +        if (bestFriendsList.length === 0) {
Почему не `!bestFriendsList.length`?

2019-01-05 09:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2019-01-06 08:07 UTC, chrighter approved these changes

2019-01-06 08:07 UTC, chrighter commented on lib.js
>      let bestFriendsList = bestFriends(friends);
`bestFriends` -> `getBestFriends`

2019-01-06 08:07 UTC, chrighter commented on lib.js
> +        result = pushNewElement(filter, nowValue, checkList, result);
`result` тоже непонятно

2019-01-06 08:07 UTC, chrighter commented on lib.js
>  function sorts(friend) {
Здесь лучше передавать `friends`, сейчас получается, что ты как-то одного друга сортируешь

2019-01-06 08:07 UTC, chrighter commented on lib.js
>          let nowValue = bestFriendsList.pop();
`nowValue` - непонятно

2019-01-06 08:08 UTC, closed without merging