Акишкина Вероника
urfu-2018/javascript-task-5 pull request #81
Opened 2018-11-25 18:04 UTC by AirenLaird

first

2018-11-25 18:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-25 18:20 UTC, AirenLaird commented
🔔

2018-11-26 07:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-26 08:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 24

2018-11-26 13:03 UTC, Dotokoto commented on lib.js
> +            value: 'female',
Можно сделать более универсальный код, если в фильтре задавать фильтрующую функцию. Тогда можно будет применять не только для разделения по полу, а как угодно. Как пример:
`checkFilter: friend => friend.gender === 'female'`

2018-11-30 13:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 14:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 14:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 14:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 14:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 15:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 15:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 16:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 24

2018-11-30 16:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-11-30 16:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-30 16:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-11-30 17:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-11-30 18:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-30 18:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-12-06 15:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-12-06 15:39 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 24

2018-12-06 15:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 24

2018-12-06 15:46 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-09 17:11 UTC, dotokoto requested changes
Еще есть, где улучшить )

2018-12-09 17:11 UTC, dotokoto commented on lib.js
> +Filter.prototype.splitBySex = function (friends) {
1) функция `splitBySex` лишняя, можно обойтись одним `checkFilter`
2) А вместо `default` можно сделать 
```
Filter.prototype.checkFilter = function () {
    return true;
};
```

2018-12-09 17:11 UTC, dotokoto commented on lib.js
> +    this.friends = friends;
Этот же код повторяется в `Iterator`, от которого наследуешься. Лучше бы его переиспользовать, не копируя

2018-12-09 17:11 UTC, dotokoto commented on lib.js
> +        throw new TypeError();
Хорошо бы дописать текст ошибки, чтобы было понятно, почему она произошла

2018-12-09 17:11 UTC, dotokoto commented on lib.js
> +    let levelFriends = friends.reduce((bestFriends, friend) => {
тут можно было просто `friends.filter(friend => friend.best)`, потому что несколько одинаковых людей в массиве быть не должно

2018-12-09 17:11 UTC, Dotokoto commented on lib.js
> +    levelFriends.forEach(bestFriend => {
Сюда ведь не только `bestFriend` попадают, это только при первом вызове

2018-12-09 17:11 UTC, Dotokoto commented on lib.js
> +                level: 1
сейчас у тебя `level` записывается в каждого друга, хотя он там не нужен. Нужно только знать, когда дошли до ограничения. Можно обойтись одной переменной

2018-12-09 17:11 UTC, Dotokoto commented on lib.js
> +            if (invited.concat(newLevelFriends)
Конкатенация - достаточно тяжелая операция, тем более, если ее во вложенном цикле выполнять. Можно переписать производительнее:
1) Сначала собираешь в один массив всех друзей друзей (bestFriend.info.friends), тут как раз будет конкатенация
2) получаешь о них информацию (то что у тебя в `friends.find(...)`
3) Отфильтровываешь тех, которые уже есть во взятых друзьях, или уже встречались в массиве друзей друзей

2018-12-10 17:57 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-10 18:16 UTC, AirenLaird commented on lib.js
> +        throw new TypeError();
Текст ошибки написала строчкой через плюсик из-за ограничения в 80 символов

2018-12-10 19:36 UTC, AirenLaird commented on lib.js
> +    let levelFriends = friends.reduce((bestFriends, friend) => {
в эту функцию у меня приходит массив, в котором еще не отброшены повторения (одинаковые люди), отбрасываю я их методом some в reduce и там же аккумулятору присваиваю значение и первый уровень. если я напишу просто функцию filter, как показано выше, я потеряю уровень и свой старт в решении задачи. Разве что можно было бы разбить функцию reduce на другие функции. Но зачем? reduce мне все равно будет нужен, а так я же просто пушу значение и уровень (первый) в аккумулятор для дальнейшей обработки, при двух условиях: если ранее не встречался друг с таким именем и если он лучший друг. Не понимаю нужно ли мне менять и как.

2018-12-10 19:49 UTC, AirenLaird commented on lib.js
> +                level: 1
Сделать что-то вроде объекта с именем - уровень и значением - массив из друзей этого уровня?

2018-12-10 19:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-10 20:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-10 20:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-10 20:39 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-10 20:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-14 10:47 UTC, Dotokoto commented on lib.js
> +                level: 1
Можно так, либо вообще запомнить максимальный уровень. И сделать цикл, который будет добавлять круги друзей, пока не закончатся друзья или не дойдешь до максимального уровня

2018-12-14 12:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 24

2018-12-14 12:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-14 15:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-14 15:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-14 15:07 UTC, AirenLaird commented on lib.js
> +            if (invited.concat(newLevelFriends)
сделала, но только сначала фильтрацию, потом получение информации

2018-12-14 15:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-14 15:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-14 15:48 UTC, AirenLaird commented on lib.js
> +    let levelFriends = friends.reduce((bestFriends, friend) => {
Сделала так все таки, а после этого сделала проверку, чтобы не было одинаковых друзей

2018-12-14 15:48 UTC, AirenLaird commented on lib.js
> +    levelFriends.forEach(bestFriend => {
Теперь использую parent и child

2018-12-14 17:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2018-12-14 17:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-14 17:47 UTC, AirenLaird commented on lib.js
> +                level: 1
Сделала map

2018-12-14 17:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-14 17:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-17 12:26 UTC, dotokoto commented on lib.js
> +        if (a.name > b.name) {
Для сравнения строк можно использовать `localCompare`: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
Поможет избежать проблем с русским языком, например. В задачке только английские имена, но стоит все равно такое учитывать

2018-12-17 12:26 UTC, dotokoto commented on lib.js
> +    while (levelFriends[0]) {
Можно было сюда прокидывать maxLevel и сделать условие
`while (levelFriends[0] && level <= maxLevel)`
Тогда не придется дополнительно отфильтровывать потом по уровню

2018-12-18 15:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2018-12-18 15:25 UTC, closed without merging